name: Create new release

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v6
    - name: Install fuse and libfuse2
      run: sudo apt install fuse libfuse2

    - name: Get URUNTIME
      run: |
        set -x
        wget https://github.com/VHSgunzo/uruntime/releases/latest/download/uruntime-appimage-dwarfs-x86_64 -O uruntime
        chmod +x ./uruntime
        pwd; ls -lah

    - name: Install llvm - URUNTIME
      run: sudo apt install llvm

    - name: Get Zotero
      run: |
        set -x
        tag=1 #1
        version=$(grep -o "Zotero:.*" README.md | cut -d ' ' -f2)
        echo "Zotero version: $version - Tag: $tag"

        mkdir squashfs-root/
        cd squashfs-root/

        file_name="Zotero-${version}_linux-x86_64.tar.xz"
        wget -q "https://download.zotero.org/client/release/$version/$file_name"
        tar -xvf "$file_name"

        rm -v "$file_name"
        pwd; ls -lah

    - name: Make AppImage
      run: |
        set -x
        tag=1 #1
        version=$(grep -o "Zotero:.*" README.md | cut -d ' ' -f2)
        echo "Zotero version: $version - Tag: $tag"
        file_name="Zotero-${version}-${tag}_JB-x86_64.AppImage"

        cd squashfs-root/

        echo '#!/bin/bash
        HERE="$(dirname "$(readlink -f "${0}")")"
        EXEC="${HERE}/Zotero_linux-x86_64/zotero"
        exec "${EXEC}"' > AppRun
        chmod +x AppRun
        cat AppRun

        ln -s Zotero_linux-x86_64/zotero.desktop Zotero.desktop
        chmod +x Zotero.desktop
        cat Zotero.desktop

        ln -s Zotero_linux-x86_64/icons/icon128.png Zotero.png
        pwd; ls -lah

        cd ../
        pwd; ls -lah

        #ARCH=x86_64 VERSION="${version}-1_JB" ./appimagetool-x86_64.AppImage squashfs-root/

        # Add update information to runtime
        UPINFO="gh-releases-zsync|$(echo "$GITHUB_REPOSITORY" | tr '/' '|')|latest|*dwarfs-$ARCH.AppImage.zsync"
        echo "Adding update information \"$UPINFO\" to runtime..."
        printf "$UPINFO" > data.upd_info
        llvm-objcopy --update-section=.upd_info=data.upd_info \
            --set-section-flags=.upd_info=noload,readonly ./uruntime
        printf 'AI\x02' | dd of=./uruntime bs=1 count=3 seek=8 conv=notrunc

        echo "Generating AppImage..."
        ./uruntime --appimage-mkdwarfs -f \
            --set-owner 0 --set-group 0 \
            --no-history --no-create-timestamp \
            --compression zstd:level=22 -S26 -B8 \
            --header uruntime \
            -i ./squashfs-root -o $file_name

        echo "Generating zsync file..."
        zsyncmake "$file_name" -u "$file_name"

        # Copy of Zotero LibreOffice Integration to the release
        cp squashfs-root/Zotero_linux-x86_64/integration/libreoffice/Zotero_LibreOffice_Integration.oxt .

        md5sum "$file_name" > "${file_name}.md5"
        pwd; ls -lah

    - uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "Zotero*.AppImage; Zotero*.zsync; Zotero*.md5; Zotero_LibreOffice_Integration.oxt"
        #overwrite: true
        verbose: true
        draft: false
        default_release_name: "Zotero V in AppImage"
